# Input/output configuration
input_dir: /Users/danielshin/Desktop/URAP/heptrkx-gnn-tracking/train_1_event
output_dir: /Users/danielshin/Desktop/URAP/heptrkx-gnn-tracking/train_1_output
n_files: 1

# Graph building configuration
selection:
    pt_min: 1 # GeV
    phi_slope_max: 0.001
    z0_max: 200
    n_phi_sections: 4
    n_eta_sections: 1
    eta_range: [-5, 5]
