data_config:
    input_dir: /Users/danielshin/Desktop/URAP/GammaAI/pairidentification/heptrkx-gnn-tracking/hitgraphs_small_000
    name: hitgraphs
    n_train: 1
    n_valid: 0
    batch_size: 1

experiment_config:
    name: gnn
    output_dir: /Users/danielshin/Desktop/URAP/GammaAI/pairidentification/heptrkx-gnn-tracking/results/gnnsegclf_001

model_config:
    model_type: 'gnn_segment_classifier'
    input_dim: 3
    hidden_dim: 64
    n_iters: 4
    loss_func: 'BCELoss'
    optimizer: 'Adam'
    learning_rate: 0.001

train_config:
    n_epochs: 16
